export const CART_REQUEST = "CART_REQUEST";
export const CART_FAILURE = "CART_FAILURE";

export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";